version: "2"
services:
  webserver:
    container_name: oro_webserver
    image: treenity/orocommerce:latest
    depends_on:
      - mysql
    links:
      - mysql
      - mailhog
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - "./:/var/www/html"
    environment:
      ENABLE_XDEBUG: 0
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=localhost"

  mysql:
    container_name: oro_mysql
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orocommerce
      MYSQL_USER: orocommerce
      MYSQL_PASSWORD: orocommerce
    volumes:
      - "mysql:/var/lib/mysql"

  mailhog:
    container_name: oro_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql:
    driver: local
